version: "3"
services:
  bitjobboard:
    container_name: "bitjobboard"
    env_file:
     - ./.env
    restart: always
    image: bitjobboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:5000"
  monstache:
    image: rwynn/monstache:4.17.3
    container_name: monstache
    working_dir: /app
    env_file:
     - ./monstache/.env
    command: -f ./config.toml -verbose
    volumes:
      - ./monstache/config.toml:/app/config.toml
    restart: always
#  bjb-nginx:
#    image: nginx
#    volumes:
#      -  "mydata:/www/devdesktop.com"
#    environment:
#    - CONTAINER_IP=bitjobboard
#    build:
#      context: .
#      dockerfile: nginx/Dockerfile
#    ports:
#    - "8080:80"
#    links:
#    - bitjobboard
#    depends_on:
#    - bitjobboard
#
#volumes:
#  mydata:
